# Generated by Django 5.1.7 on 2025-03-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VisionTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("speed_mode", models.BooleanField(default=False)),
                ("field_left", models.IntegerField(default=0)),
                ("field_right", models.IntegerField(default=0)),
                ("missed_count", models.IntegerField(default=0)),
            ],
        ),
    ]
